env: "local"
default-max-retries: 3
db:
   url: "postgres://Lenovo:123456@localhost:5432/taskmanager-db?sslmode=disable"
redis:
  address: "localhost:6379"
  password: ""
  database: 0

scheduler:
  stale-task-threshold: 2m

server:
  address: "localhost:8081"
  timeout: 4s
  iddle_timeout: 60s

auth:
  jwt-secret: "super-secret-key-change-in-production"
  jwt-expiration-hours: 72
  google-client-id: ""
  google-client-secret: ""
  github-client-id: ""
  github-client-secret: ""
  oauth-callback-url: "http://localhost:3000"

mailhog:
  host: "localhost"
  port: 1025
  username: ""
  password: ""