env: "local"
db:
   url: "postgres://Lenovo:123456@localhost:5432/taskmanager-db?sslmode=disable"
redis:
  address: "localhost:6379"
  password: ""
  database: 0

scheduler:
  stale-task-threshold: 2m

server:
  address: "localhost:8080"
  timeout: 4s
  iddle_timeout: 60s

mailhog:
  host: "localhost"
  port: 1025
  username: ""
  password: ""